sudo: required
services:
    - docker
before_install:
    - docker build -t dbernat/fibotest -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dbernat/fibotest npm run test

after_success:
    - docker build -t dbernat/fibo-client-k8s   ./client
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push dbernat/fibo-client-k8s